use_frameworks!

platform :ios, '10.0'

target 'KonkeSdk4YinYue_WebSocket_Example' do
  pod 'KonkeSdk4YinYue_WebSocket', :path => '../'

  target 'KonkeSdk4YinYue_WebSocket_Tests' do
    inherit! :search_paths

    
  end
end
